[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
python_version = "3.11"
# strict = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [
	"mwparserfromhell.*",  # https://github.com/earwig/mwparserfromhell/issues/306
	"pywikibot.*",
]
ignore_missing_imports = true
